AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the Example::GitHub::Repo resource type

Globals:
  Function:
    Timeout: 60  # docker start-up times can be long for SAM CLI

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      CodeUri: bin/
      # Uncomment to test with AWS resources
      # Environment:
      #   Variables:
      #     AWS_FORCE_INTEGRATIONS: "true"

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      CodeUri: bin/
